### ISSUE TITLE
Failed parse using external (relative) template

### ISSUE THREAD

**Issue by laggingreflex** [vuejs/vue-jest#176]
Similar (but slightly different) to https://github.com/vuejs/vue-jest/issues/45

Using relative templates but I still have an issue. The templates do get parsed, but I think they're not "interpreted" correctly. 

Repro: https://github.com/laggingreflex/repro-vue-jest-template

It works in the browser but running jest it gives this error

```
> jest
Cannot use <template> as component root element because it may contain multiple nodes.
 FAIL  src/test.js
  ● Test suite failed to run
```

Taking hint from the error, if I change my `App/template.vue` from 

```vue
<template>
  <div>App</div>
</template>
```
to just
```vue
  <div>App</div>
```
the test passes, but that's not the correct format for template - the app doesn't work in the browser.

**Comment by LinusBorg** [comment]
> but that's not the correct format for template

Well, the external file that you include should be .html, not .vue

```html
<template src="./template.html">
```

including another .vue file was never a use case for SFCs.

**Comment by eddyerburgh** [comment]
As @LinusBorg says, external .vue files aren't part of the [SFC spec](https://vue-loader.vuejs.org/spec.html#src-imports)

**Comment by MarcelReis** [comment]
@eddyerburgh I'm switching to `.html` files for a fix, but I think vue-jest should consider adding support to `.vue`

- `vue-template-compiler` compiles external `.vue` files, `vue-loader` should also, otherwise we can end up with a bunch of broken tests.
- For sure, it's not part of the SFC spec, but it would be a nice increment, using the template file as `.vue` provides better IDE support.
