### ISSUE TITLE
v4 still in beta

### ISSUE THREAD

**Issue by sibiraj-sr** [vuejs/vue-jest#206]
V4 beta was released long back. is there anything still pending. So far everything works fine I guess. 
Perhaps it's safe to release v4.0.0

**Comment by sibiraj-sr** [comment]
@eddyerburgh

**Comment by telion2** [comment]
I would also like to encourage a release. I ran into some wierd compatibility issues with babel, core-js 3 and vue-jest 3, which got resolved by updating to vue-jest 4beta.  
I think this issue was part of the problem: https://github.com/vuejs/vue-cli/issues/5125 

Maybe the contributes, could provide a link or list of things that need to be done before v4 can be released? 
Even though vue-jest is used as dev-dependencies, my clients see beta packages as risks, even though like in this case the package is fine.

**Comment by lmiller1990** [comment]
I moved to release candidate as of right now.

We can move to 4.0.0 soon. There are few PRs I would like to merge first. Let's make this happen before the end of September - ping me if needed. Most of the team is focused on Vue 3 now but we should still make this hit a proper 4.0.0 release.

**Comment by n1ngu** [comment]
For the record, v4.0.0-rc1 was published this december https://github.com/vuejs/vue-jest/releases/tag/v4.0.0-rc.1

Yet, we are clearly not on track to

> Let's make this happen before the end of September

so here's your ping, @lmiller1990 :)

Not that I want to cause any hassle! Just checking out this thread because I was surprised about this ubiquitous pre-release installed across many of my team's projects, and the absence of a 4.0 release while may 5.0-alphas can be already found in the npm registry.

Is there anything blocking the release besides lack of manpower? (due to other higher priorities, etc, totally understandable) Is there a roadmap for what is missing where the community can help in any way?

**Comment by lmiller1990** [comment]
There is nothing really stopping a 4.0 release other than no clear goal - eg, what makes it 4.x instead of just rc? There is many outstanding improvements but from what I can tell everything generally works fine.

I can just do a release this week and call it 4.x if that will make people happy. What do you think? If you want to look over the issues and see if there is any obvious blocker, that'd be great.

I need to spend some time to triage issues - most focus has been on 5.x and various other parts of the Vue 3 ecosystem.

**Comment by n1ngu** [comment]
I guess precisely the pre-release stability plus the lack of a clear goal make the latest rc a valid 4.0 release as-is? I think that was @sibiraj-sr intent when opening this issue.

And I guess, if nobody has hassled about the open issues present from the 3.x series... they can just wait for the 4.0.1? I'd like to help triaging them but I fear I'd be useless: I have no experience with this tool, I'm just that weird guy watching lock files and wondering about life.

Then again this is rather unimportant because vue-jest is usually used as a dev-dependency, but it will probably help people deduplicating transient dependencies if they are being picky about pre-releases.

Cheers and thanks for your work! Keep on track for the 5.0, we are expectant!

**Comment by lmiller1990** [comment]
Hi guys, I have not forgotten this, I will do it in a few days - busy! I want to spend a few hours really making sure we did not miss anything before dropping 4.0 (I think it's pretty stable by this point, but you know).

**Comment by lmiller1990** [comment]
It's out: https://github.com/vuejs/vue-jest/releases/tag/v4.0.0

**Comment by lmiller1990** [comment]
Install with `yarn add vue-jest@4.0.0`.
