### ISSUE TITLE
Jest 26?

### ISSUE THREAD

**Issue by jnardone** [vuejs/vue-jest#247]
Can we update peer dependencies to use Jest 26?  This would also mean moving ts-jest to 26.x.x.

**Comment by lmiller1990** [comment]
Didn't Jest 26 just come out? 

I wonder if there is any breaking changes we need to be aware of. 

Also, is there any strong benefit to change the peerDependency version? It's "^25", or "at least 25". It is good to keep dependencies up to date.

**Comment by jnardone** [comment]
^25 doesn’t include major version bumps. 

Jest 26 came out May 5, two months ago.

**Comment by lmiller1990** [comment]
Ok. I think we need a good strategy for versions, and if there are any associated breaking changes.

We could continue discussing this here: https://github.com/vuejs/vue-jest/pull/246

**Comment by jnardone** [comment]
One thing would be to version in conjunction with jest.  So vue-jest 25.x is for jest 25.x, 26.x for 26.x, etc.

**Comment by lmiller1990** [comment]
I had this idea - I like this. How to specify Vue 2 and Vue 3 though? The codebases are quite different.

**Comment by TheJaredWilcurt** [comment]
I've been pinning all my repos to `"jest": "24.9.0"` until they can fix the color diffing bug that happens on many platforms and CI's:

* https://github.com/facebook/jest/issues/9459

**Comment by ahnpnl** [comment]
How about <jest_major_ver>.<vue_major_ver>.<sequence_ver> For example: 

26.3.0 means:
- Compatible with Jest 26
- Compatible with Vue 3 
- Any bug fixes/new features of `vue-jest`

Following this satisfying both issues with jest and Vue. If following this approach, documentation should be modified to warn users about not following sem ver

**Comment by lmiller1990** [comment]
I think this is a good idea. Yesterday some code was merged to 4.x but not 5.x - having two effectively different libs in one repo doesn't make sense.

I will work on separating the two repos soon. Then we can follow the pattern of matching the Jest version.

**Comment by ahnpnl** [comment]
I think monorepo or yarn workspace can help to maintain things like that. You can check how `jest` done. The structure will be like:

- packages
     + vue-jest-2
     + vue-jest-3
     + vue-jest-4
     ...

Then you can configure CI CD or manually publish each independent package.

**Comment by vvanpo** [comment]
Is there a reason we constrain `jest` to a specific major version? I've been using `vue-jest` with Jest 26 without problems, so clearly a version constraint like `^25 || ^26` would work. Likely we could go even laxer, like `>= 24`. I don't think we should be over-constraining peer dependencies unless we have a specific compatibility reason for doing so.

**Comment by vvanpo** [comment]
@ahnpnl that only takes into account the Jest version. But there is the Vue version to consider too. And since `vue-jest` actually as 3 independent peer dependencies, we have to add `@babel/core` to the list too. But trying to account for all of these by publishing distinct subpackages in a monorepo would lead to a combinatorial explosion of subpackages, I don't think that's feasible.

**Comment by vvanpo** [comment]
> In vue-jest-3 package, you can have: v24, v25, v26 etc which stands for jest compat

If by v24, etc. you mean those would be version tags, that would limit `vue-jest` to only publishing breaking changes at the same cadence as `jest`. That's probably not a big deal, because we likely don't have much of a need for making breaking changes all that often, but still doesn't make too much sense IMO. In all likelihood the changes between Jest version compatibility of v24 vs v26 are fairly minimal, and if there are any issues we can probably manage them with conditionals checking the currently loaded Jest version. Having three separate branches means that every bug fix and feature will need to be backported twice. I think we'd be better off just updating our test runner to run 3 times, once for each version of Jest v24, v25, and v26. That would help us ensure `vue-jest` remains compatible. I'm happy to make a PR for that if that sounds like a good idea.

> Yesterday some code was merged to 4.x but not 5.x - having two effectively different libs in one repo doesn't make sense.

@lmiller1990 if you're referring to my changes to Sass' importer, I'm sorry about that my intention was not to cause the two branches to diverge. I fully intend to open another PR to cherry-pick those changes to 5.x, but I'd like to explore a different solution first (https://github.com/webpack-contrib/sass-loader/issues/873) and am waiting to hear how that pans out.

**Comment by lmiller1990** [comment]
@vvanpo Yep no problem, I don't mind if we diverge a bit - the codebases between `master` and `next` are not too different, we should cherry pick the commits, but no rush - I think we should definitely figure out how we can make this entire code base more maintainable and share common features across Vue 2.x and 3.x.

Regarind Jest versions, I am in the same position as you - I have noticed no problems with both Jest 25 and 26, but there seems to be a pretty common convention with Jest transformers to pin their versions to Jest. Seems like it's good to follow the convention.

That said it might just add *more* complexity. Ideally we want to support both Vue 2.x and Vue 3.x across each version of Jest. I have no idea what the differences are in Jest 25 and 26, maybe we can just support the latest major version of Jest (it is really difficult to upgrade Jest versions? I don't think so? I've always just added the latest Jest without even thinking about what version I'm adding).

Ideally we will separate the Vue 2.x and Vue 3.x specific logic and use the same transformers (eg for sass, coffeescript, whatever) across both integrations.

**Comment by lmiller1990** [comment]
4.x is now in RC and on Jest 26.
