### ISSUE TITLE
Please release v27

### ISSUE THREAD

**Issue by ninjabhishek** [vuejs/vue-jest#458]
Hi,

Please release v27 so the depending libraries can use them to publish their versions, and apps can use a proper release. Using rc is discouraged in enterprise environment.

**Comment by lmiller1990** [comment]
Sure, we can move to v27 stable. Right now CI is failing on master, and I don't know why. 

I'm trying to find out why. If anyone would like to accelerate this v27 release, some assistance would be greatly appreciated. I do not use Vue Jest in a production or paid environment, so if this is really critical to your organization (assuming it is, since this issue has many :+1:s), please send some time to help get the master branch CI to be green so we can release it.

**Comment by lmiller1990** [comment]
Ok, seems fixed: https://github.com/vuejs/vue-jest/commit/328427c901c13025725b4cd774f9a8d0de636767

**Comment by ninjabhishek** [comment]
So we on for a release soon?

**Comment by lmiller1990** [comment]
Yes it's done now. I hope it's working as expected. https://github.com/vuejs/vue-jest/releases/tag/v27.0.0

If not, please log an issue. Also note the info at the top of the release: I'm not really using Jest much now-days, so my bandwidth to fix things is pretty low. If you are one of the enterprise users, please try to spend some of your work time to fix bugs.
